const main = document.getElementById("0");
const header = document.getElementById("cheader");
const paragraph = document.getElementById("cpar");

function zmien(e, nr) {
    e.preventDefault();
    if (nr === 1) {
        header.innerHTML = "<i class='icon-home' ></i> Strona Domowa";
        paragraph.innerHTML = 'Siema elo siemandero! Z tej strony Pefek, albo Pefek45, albo xmelonek123... Wracając, to moja główna strona internetowa, tu będę trzymał również historię Xilan Studio i wgl moją. <br><h2>Namiary</h2><br> <i class="icon-mail-alt" title="Wyślij mi maila!"> </i> E-Mail: pefek45@outlook.com <br> <i class="icon-github-squared" title="Spójrz, jestem na Github!"> </i><a href="https://github.com/pefek-git?tab=repositories" target="_blank">GitHub</a><br> <i class="icon-youtube" title="Zobacz moje filmy!"> </i><a href="https://www.youtube.com/@Pefek45" target="_blank">Głowny kanał na Youtube</a> ';
    }
    else if (nr === 2) {
        header.innerHTML = "<i class='icon-user' ></i> Kim ja jestem?";
        paragraph.innerHTML = "Jestem małym twórcą na yt, w podzakładce Namiary macie mój e-mail, link do kanału etc. Moja przygoda z platformą Youtube zaczęła się dośc dawno temu bo aż w 2018 roku! pomyśleć że w chwili gdy to pisze to było 8 lat temu... WRACAJĄC! Mój pierwszy kanał na Yt się nazywał nie xmelonek123 tylko krisgameplayer20, na którym w peaku miałem 20 subów. Dziś mam ten kanał i moja liczba subów na 17 marca wynosi 63 subskrybentów! Dzięki za wszystkie suby! <br><h2><i class='icon-hourglass-1'></i>Jak zaczynałem?</h2><br>Jak miałem siedem lat to dostałem swój pierwszy laptop na własność z czego jestem szczęśliwy, BTW to był Dell Latitude E6410 z 4GB RAM; Intel Core i5 M520, i jakaś stara NVIDIA, prawdopodobnie NVS 3100M 512MB, ale dawałem radę na nim grać w Minecraft z kilkoma modami i oglądać Youtube'a. Dla porównania dziś używam HP Victus 15 z Intel Core i5 12 generacji, 16GB RAM i NVIDIA RTX 3050.<br><h2>Co potem?</h2><br> Kiedy miałem 8 lat to zacząłem pisać jakieś proste strony internetowe, tutaj muszę podziękować <a href='https://www.youtube.com/@Pasjainformatyki' target='_blank' title='Kliknij mnie a nie pożałujesz'>Pasja Informatyki</a> za spędzony czas przed ekranem który nie był stracony. Dzięki temu kanałowi nauczycie się jak nawet zwykły chlebojad może zrobić prostą ale gotową stronę. Dziś mam 14 lat i wiecie co, niczego nie żałuje, mam własne 'studio', dobrych ziomków a nawet ekipę.<br><h2><i class='icon-gamepad' ></i>Ulubiona wersja Minecraft</h2><br>Szczerze moja ulubiona wersja Minecraft to do tej pory 1.12.2, ilość modów jakie na nią wyszła jest niezliczona przynajmniej przeze mnie. <br><h2><i class='icon-cog-alt' ></i>System Operacyjny</h2><br> Swoją drogą od końca grudnia 2025 już nie używam Windows jako głównego systemu operacyjnego, aktualnie na Victusie używam dystrybucji Linuxa Fedora 42 ze środowiskiem KDE, lecz wcześniej miałem na nim CachyOS ale coś się zepsuło i zmieniłem system na Fedora z KDE. Plusem KDE moim zdaniem jest fakt że instalacja X11 jest prostsza niż na Fedora Workstation (z GNOME). <br>Natomiast na laptopie zapasowym mam Linux Arch również ze śrowdowiskiem graficznym KDE Plasma. Wybrałem Archa nie dlatego, że jestem masochistą, tylko dlatego, że Arch daje nam pełną kontrolę nad systemem, a dlaczego KDE? Bo jest praktycznie w pełni customizowalne i to są cechy które właśnie lubie. <br><h2>Jakie plany?</h2><br> Cóż, zamierzam stworzyć własny framework do gier w Godot, będzie open-source i do gier FPS, wg. mnie będzie się nazywał Epsilo Framework. Kanał na Youtube będzie wciąż kontynuowany chyba że stracę wenę.";
    }
    else if (nr === 3) {
        header.innerHTML = "<i class='icon-newspaper' ></i> Nowiny";
        paragraph.innerHTML = "Póki co nic nowego :<)";
    }
    else if (nr === 4) {
        header.innerHTML = "<i class='icon-lightbulb' ></i> Kulisy";
        paragraph.innerHTML = "Za kulisami jestem pisarzem stron i bawie się w Godot, jak przy wspomnianym wcześniej Epsilo Framework. <br><h2>Czy jakieś gry?</h2><br> Owszem tak!, na Epsilo Framework zamierzam stworzyć własną grę, będzie się nazywać The Shadow. Pewnie wersja sandboxowa silnika róœnież do was trafi pod nazwą Epsilo Playground!";
    }
    else if (nr === 5) {
        header.innerHTML = "<i class='icon-gamepad' ></i> Gry";
        paragraph.innerHTML = '<h1>Epsilo Playground</h1><br> To będzie sandboxowa wersja Epsilo Framework, możliwe, że będzie multiplayer albo wyjdzie na telefony, ale wszystko w swoim czasie. Do zabawy dodam kilka broni, NPC i dwie mapy.<br><h1>The Shadow</h1><br> To prawdopodobnie będzie pierwsza porządniejsza gra ode mnie, powstanie na Epsilo Framework. <h3>TL;DR:</h3>The Shadow to mroczna historia o upadku człowieka, samotności i świecie, który przestał mieć zasady. <br><h2>Kto jest głównym bohaterem?</h2><br>Jej głównym bohaterem będzie Lee Bloodwood, nihilistyczny, psychopatyczny morderca przyodziany w jeansy, czarny skórzany płaszcz, czarna fedora i nieodłączna strzelba, brudna od prochu, dusz i krwi jego ofiar. Gra będzie inspirowana POSTAL&copy; 1997/Redux, modem The Pink Valley i Hatred. Główny bohater miał ciężko-ciekawą historię, już w szkole był prześladowany przez znajomych, bili go i wyzywali, wtedy właśnie odkrył grę CT Strike. To była prosta strzelanka FPS, coś jak CS i tak przez 3 miesiące grał offline aż w końcu gdy stwierdził że jest już wystarczająco dobry to wszedł na forum dla graczy i potem zaczął grać online, lecz po następnych 3 miesiącach grania online i zdobywania nowych znajomości, jego prześladowca odkrył go na forum i zaczął go szkalować, wyzywać od idiotów, inceli i rednecków oraz grożąc mu śmiercią. Lee wtedy zrozumiał, że nawet w tym co on kocha znajdą się jego oprawcy. Terapeuta zalecił, by kupił sobie kota, do zabawy. Lee był bardzo przywiązany do zwierzęcia, lecz niestety, po 4 latach posiadania kota, prześladowca - Thomas Liebenstein, zabił zwierzę. Wtedy Bloodwood nie wytrzymał, poszedł do sejfu, wyciągnął i załadował strzelbę i zabił prześladowcę. Od tamtej pory Lee wpadł szał, (po angielsku: "He went Postal") i chyba nie muszę tłumaczyć co działo się na ulicach... <br><h2>Gdzie się dzieje akcja?</h2><br> Akcja dzieje się w fikcyjnym miasteczku Hellborough, które jest strasznie dziwne, praktycznie nikt w tym mieście nie jest zdrowy psychicznie. Mieszkańcy spalili kościół, a na jego miejscu powstał bar. Miasto ma klimat mroku i niepokoju, "Już policja tu zabija wszystkich, nie patrzą na twarz." wpis z dziennika Bloodwooda. ';
    }
}